version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    restart: always

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx:/etc/nginx:ro
#    depends_on:
#      - node-app

  webserver:
    image: abiosoft/caddy
    restart: always
    environment:
      - ACME_AGREE=true
      - CADDYPATH=/etc/caddycerts
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile
      - ./docker/caddy/caddyssl:/etc/caddycerts
      - ./:/app
    depends_on:
      - node-app